---
title: "India Air Quality Index Prediction"
author: "Kshitiz Sahay"
date: "2024-05-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width = 10, fig.height = 6)
setwd("/Users/kshitizsahay/Downloads")
options(width = 200)
```

# Import Packages

```{r, message=FALSE, warning=FALSE}
Sys.setlocale("LC_TIME", "English")
library(readr)
library(xts)
library(forecast)
library(tseries)
library(fGarch)
library(TSA)
library(Metrics)
library(prophet)
library(dplyr)
```

# Import Datasets

```{r}
cities <- c('Bengaluru', 'Lucknow', 'Delhi', 'Chennai')

for (city in cities) {
  file_name <- paste0(city, "_day_filled.csv")
  assign(city, read.csv(file_name))
  print(city)
  print(rbind(head(get(city), 3), tail(get(city), 3)))
}
```

# Create XTS objects

```{r}
for (city in cities) {
  data <- get(city)
  data$Date <- as.Date(data$Date)
  city_xts <- xts(data[,-1], order.by = data$Date)
  assign(paste0(city, "_xts"), city_xts)
  print(city)
  print(rbind(head(get(paste0(city, "_xts")), 3), tail(get(paste0(city, "_xts")), 3)))
}
```

# EDA

```{r}
cities <- c('Bengaluru', 'Lucknow', 'Delhi', 'Chennai')
cities_xts <- c('Bengaluru_xts', 'Lucknow_xts', 'Delhi_xts', 'Chennai_xts')

plot(Bengaluru_xts$AQI)
plot(Lucknow_xts$AQI)
plot(Delhi_xts$AQI)
plot(Chennai_xts$AQI)
```

```{r}
eda_ts <- function (xts, city_name) {
  acf(xts$AQI, main = paste("ACF for", city_name))
  pacf(xts$AQI, main = paste("PACF for", city_name))
}

for (city in cities_xts) {
  eda_ts(get(city), city)
}
```

```{r}
adf.test(Bengaluru_xts$AQI)
kpss.test(Bengaluru_xts$AQI)
eacf(Bengaluru_xts$AQI)

adf.test(Chennai_xts$AQI)
kpss.test(Chennai_xts$AQI)
eacf(Chennai_xts$AQI)

adf.test(Delhi_xts$AQI)
kpss.test(Delhi_xts$AQI)
eacf(Delhi_xts$AQI)

adf.test(Lucknow_xts$AQI)
kpss.test(Lucknow_xts$AQI)
eacf(Lucknow_xts$AQI)
```

# Decompose

```{r}
for (city in cities_xts) {
  plot(decompose(ts(get(city)$AQI, frequency = 365)), col.main = "white")
  title(main = paste("Decomposition of additive time series for", city))
}
```

# Train / Test Split

```{r}
for (city in cities_xts) {
  train_data <- window(get(city),
                       start = as.Date("2015-01-01"),
                       end = as.Date("2020-06-01"))
  test_data <- window(get(city),
                      start = as.Date("2020-06-02"),
                      end = as.Date("2020-07-01"))
  assign(paste0(city, "_train"), train_data)
  assign(paste0(city, "_test"), test_data)
}
```

# Models

```{r}
# Convert xts objects to dataframes
df_train <- data.frame(date = index(Lucknow_xts_train), coredata(Lucknow_xts_train))
df_test <- data.frame(date = index(Lucknow_xts_test), coredata(Lucknow_xts_test))

# Rename columns for Prophet
df_train <- df_train %>% rename(ds = date, y = AQI)
df_test <- df_test %>% rename(ds = date, y = AQI)

# Initialize the Prophet model
m <- prophet(daily.seasonality=TRUE)

# Add the additional regressors
m <- add_regressor(m, 'PM2.5')
m <- add_regressor(m, 'NO')
m <- add_regressor(m, 'NO2')
m <- add_regressor(m, 'CO')

# Fit the model
m <- fit.prophet(m, df_train)

# Make a future dataframe only for the required periods (30 in this case)
past <- df_train[, c('ds', 'PM2.5', 'NO', 'NO2', 'CO')]

# Forecast
forecast0 <- predict(m, past)

# Plot the forecast
plot(m, forecast0)
prophet_plot_components(m, forecast0)

# Make a future dataframe only for the required periods (30 in this case)
future <- df_test[, c('ds', 'PM2.5', 'NO', 'NO2', 'CO')]

# Forecast
forecast <- predict(m, future)

# Plot the forecast
plot(m, forecast)
prophet_plot_components(m, forecast)

# Extract actual values from the test set
actual <- df_test$y

# Extract predicted values from the forecast
predicted <- forecast$yhat

# Calculate metrics
rmse_value <- rmse(actual, predicted)
mse_value <- mse(actual, predicted)
mape_value <- mape(actual, predicted)
mae_value <- mae(actual, predicted)
amape_value <- mean(abs((actual - predicted) / ((actual + predicted) / 2))) * 100

# Print the metrics
cat("RMSE: ", rmse_value, "\n")
cat("MSE: ", mse_value, "\n")
cat("MAPE: ", mape_value, "\n")
cat("MAE: ", mae_value, "\n")
cat("AMAPE: ", amape_value, "\n")

# Calculate Residuals
residuals <- actual - predicted

# Calculate Residual Sum of Squares (RSS)
rss <- sum(residuals^2)

# Number of observations and number of parameters
n <- length(actual)
k <- length(m$params)

# Calculate Log-Likelihood
log_likelihood <- -n/2 * (log(2 * pi) + log(rss/n) + 1)

# Calculate AIC
aic <- 2 * k - 2 * log_likelihood

# Calculate BIC
bic <- log(n) * k - 2 * log_likelihood

# Print the metrics
cat("AIC: ", aic, "\n")
cat("BIC: ", bic, "\n")
```

```{r}
# Convert xts objects to dataframes
df_train <- data.frame(date = index(Chennai_xts_train), coredata(Chennai_xts_train))
df_test <- data.frame(date = index(Chennai_xts_test), coredata(Chennai_xts_test))

# Rename columns for Prophet
df_train <- df_train %>% rename(ds = date, y = AQI)
df_test <- df_test %>% rename(ds = date, y = AQI)

# Initialize the Prophet model
m <- prophet(daily.seasonality=TRUE)

# Add the additional regressors
m <- add_regressor(m, 'PM2.5')
m <- add_regressor(m, 'NO')
m <- add_regressor(m, 'NO2')
m <- add_regressor(m, 'CO')

# Fit the model
m <- fit.prophet(m, df_train)

# Make a future dataframe only for the required periods (30 in this case)
past <- df_train[, c('ds', 'PM2.5', 'NO', 'NO2', 'CO')]

# Forecast
forecast0 <- predict(m, past)

# Plot the forecast
plot(m, forecast0)
prophet_plot_components(m, forecast0)

# Make a future dataframe only for the required periods (30 in this case)
future <- df_test[, c('ds', 'PM2.5', 'NO', 'NO2', 'CO')]

# Forecast
forecast <- predict(m, future)

# Plot the forecast
plot(m, forecast)
prophet_plot_components(m, forecast)

# Extract actual values from the test set
actual <- df_test$y

# Extract predicted values from the forecast
predicted <- forecast$yhat

# Calculate metrics
rmse_value <- rmse(actual, predicted)
mse_value <- mse(actual, predicted)
mape_value <- mape(actual, predicted)
mae_value <- mae(actual, predicted)
amape_value <- mean(abs((actual - predicted) / ((actual + predicted) / 2))) * 100

# Print the metrics
cat("RMSE: ", rmse_value, "\n")
cat("MSE: ", mse_value, "\n")
cat("MAPE: ", mape_value, "\n")
cat("MAE: ", mae_value, "\n")
cat("AMAPE: ", amape_value, "\n")

# Calculate Residuals
residuals <- actual - predicted

# Calculate Residual Sum of Squares (RSS)
rss <- sum(residuals^2)

# Number of observations and number of parameters
n <- length(actual)
k <- length(m$params)

# Calculate Log-Likelihood
log_likelihood <- -n/2 * (log(2 * pi) + log(rss/n) + 1)

# Calculate AIC
aic <- 2 * k - 2 * log_likelihood

# Calculate BIC
bic <- log(n) * k - 2 * log_likelihood

# Print the metrics
cat("AIC: ", aic, "\n")
cat("BIC: ", bic, "\n")
```

```{r}
# Convert xts objects to dataframes
df_train <- data.frame(date = index(Delhi_xts_train), coredata(Delhi_xts_train))
df_test <- data.frame(date = index(Delhi_xts_test), coredata(Delhi_xts_test))

# Rename columns for Prophet
df_train <- df_train %>% rename(ds = date, y = AQI)
df_test <- df_test %>% rename(ds = date, y = AQI)

# Initialize the Prophet model
m <- prophet(daily.seasonality=TRUE)

# Add the additional regressors
m <- add_regressor(m, 'PM2.5')
m <- add_regressor(m, 'NO')
m <- add_regressor(m, 'NO2')
m <- add_regressor(m, 'CO')

# Fit the model
m <- fit.prophet(m, df_train)

# Make a future dataframe only for the required periods (30 in this case)
past <- df_train[, c('ds', 'PM2.5', 'NO', 'NO2', 'CO')]

# Forecast
forecast0 <- predict(m, past)

# Plot the forecast
plot(m, forecast0)
prophet_plot_components(m, forecast0)

# Make a future dataframe only for the required periods (30 in this case)
future <- df_test[, c('ds', 'PM2.5', 'NO', 'NO2', 'CO')]

# Forecast
forecast <- predict(m, future)

# Plot the forecast
plot(m, forecast)
prophet_plot_components(m, forecast)

# Extract actual values from the test set
actual <- df_test$y

# Extract predicted values from the forecast
predicted <- forecast$yhat

# Calculate metrics
rmse_value <- rmse(actual, predicted)
mse_value <- mse(actual, predicted)
mape_value <- mape(actual, predicted)
mae_value <- mae(actual, predicted)
amape_value <- mean(abs((actual - predicted) / ((actual + predicted) / 2))) * 100

# Print the metrics
cat("RMSE: ", rmse_value, "\n")
cat("MSE: ", mse_value, "\n")
cat("MAPE: ", mape_value, "\n")
cat("MAE: ", mae_value, "\n")
cat("AMAPE: ", amape_value, "\n")

# Calculate Residuals
residuals <- actual - predicted

# Calculate Residual Sum of Squares (RSS)
rss <- sum(residuals^2)

# Number of observations and number of parameters
n <- length(actual)
k <- length(m$params)

# Calculate Log-Likelihood
log_likelihood <- -n/2 * (log(2 * pi) + log(rss/n) + 1)

# Calculate AIC
aic <- 2 * k - 2 * log_likelihood

# Calculate BIC
bic <- log(n) * k - 2 * log_likelihood

# Print the metrics
cat("AIC: ", aic, "\n")
cat("BIC: ", bic, "\n")
```

```{r}
# Convert xts objects to dataframes
df_train <- data.frame(date = index(Bengaluru_xts_train), coredata(Bengaluru_xts_train))
df_test <- data.frame(date = index(Bengaluru_xts_test), coredata(Bengaluru_xts_test))

# Rename columns for Prophet
df_train <- df_train %>% rename(ds = date, y = AQI)
df_test <- df_test %>% rename(ds = date, y = AQI)

# Initialize the Prophet model
m <- prophet(daily.seasonality=TRUE)

# Add the additional regressors
m <- add_regressor(m, 'PM2.5')
m <- add_regressor(m, 'NO')
m <- add_regressor(m, 'NO2')
m <- add_regressor(m, 'CO')

# Fit the model
m <- fit.prophet(m, df_train)

# Make a future dataframe only for the required periods (30 in this case)
past <- df_train[, c('ds', 'PM2.5', 'NO', 'NO2', 'CO')]

# Forecast
forecast0 <- predict(m, past)

# Plot the forecast
plot(m, forecast0)
prophet_plot_components(m, forecast0)

# Make a future dataframe only for the required periods (30 in this case)
future <- df_test[, c('ds', 'PM2.5', 'NO', 'NO2', 'CO')]

# Forecast
forecast <- predict(m, future)

# Plot the forecast
plot(m, forecast)
prophet_plot_components(m, forecast)

# Extract actual values from the test set
actual <- df_test$y

# Extract predicted values from the forecast
predicted <- forecast$yhat

# Calculate metrics
rmse_value <- rmse(actual, predicted)
mse_value <- mse(actual, predicted)
mape_value <- mape(actual, predicted)
mae_value <- mae(actual, predicted)
amape_value <- mean(abs((actual - predicted) / ((actual + predicted) / 2))) * 100

# Print the metrics
cat("RMSE: ", rmse_value, "\n")
cat("MSE: ", mse_value, "\n")
cat("MAPE: ", mape_value, "\n")
cat("MAE: ", mae_value, "\n")
cat("AMAPE: ", amape_value, "\n")

# Calculate Residuals
residuals <- actual - predicted

# Calculate Residual Sum of Squares (RSS)
rss <- sum(residuals^2)

# Number of observations and number of parameters
n <- length(actual)
k <- length(m$params)

# Calculate Log-Likelihood
log_likelihood <- -n/2 * (log(2 * pi) + log(rss/n) + 1)

# Calculate AIC
aic <- 2 * k - 2 * log_likelihood

# Calculate BIC
bic <- log(n) * k - 2 * log_likelihood

# Print the metrics
cat("AIC: ", aic, "\n")
cat("BIC: ", bic, "\n")
```